const STUDENTS = [
  {
    id: 5,
    username: "alebal",
    name: "Aleksas",
    surname: "Balciukynas",
    vidko: "e1111",
    email: "email1@emai.com",
    phoneNumber: "+37061111111",
    faculty: 1,
    year: 1,
    homeAddress: "Kaunas, Kauno g. 1",
    gender: 1,
    academicGroup: 1,
    isStateFunded: true,
  },
  {
    id: 2,
    username: "keskaz",
    name: "Kestutis",
    surname: "Kazlauskas",
    vidko: "e2222",
    email: "email2@emai.com",
    phoneNumber: "+3706222222",
    faculty: 2,
    year: 2,
    homeAddress: "Kaunas, Kauno g. 2",
    gender: 2,
    academicGroup: 2,
    isStateFunded: true,
  },
  {
    id: 3,
    username: "jonjon",
    name: "Jonas",
    surname: "Jonauskas",
    vidko: "e3333",
    email: "email3@emai.com",
    phoneNumber: "+370633333",
    faculty: 3,
    year: 3,
    homeAddress: "Kaunas, Kauno g. 3",
    gender: 3,
    academicGroup: 3,
    isStateFunded: false,
  },
];

export default STUDENTS;
